
name: push-to-docker-hub

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: Docker image tag to be applied
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Building and copying React

    - name: npm install durablefunctionsmonitor.react
      run: npm install -legacy-peer-deps
      working-directory: durablefunctionsmonitor.react
    - name: npm build durablefunctionsmonitor.react
      run: npm run build
      working-directory: durablefunctionsmonitor.react

    - name: copy statics to durablefunctionsmonitor.dotnetisolated/DfmStatics
      run: |
        rm -rf durablefunctionsmonitor.dotnetisolated/DfmStatics
        cp -r durablefunctionsmonitor.react/build durablefunctionsmonitor.dotnetisolated/DfmStatics

    # Building and testing .NET

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: dotnet test tests/durablefunctionsmonitor.dotnetisolated.core.tests
      run: dotnet test tests/durablefunctionsmonitor.dotnetisolated.core.tests/*.csproj

    - name: login to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # NOTE: build context is the repo root for all images, because the projects
    # reference durablefunctionsmonitor.dotnetisolated.core by project reference

    - name: build and push durablefunctionsmonitor.dotnetisolated
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./durablefunctionsmonitor.dotnetisolated/Dockerfile
        push: true
        tags: scaletone/durablefunctionsmonitor:${{ github.event.inputs.imageTag }}

    - name: build and push custom-backends/dotnetIsolated-mssql
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./custom-backends/dotnetIsolated-mssql/Dockerfile
        push: true
        tags: scaletone/durablefunctionsmonitor.mssql:${{ github.event.inputs.imageTag }}

    - name: build and push custom-backends/dotnetIsolated-netherite
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./custom-backends/dotnetIsolated-netherite/Dockerfile
        push: true
        tags: scaletone/durablefunctionsmonitor.netherite:${{ github.event.inputs.imageTag }}
